config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :products

  devise_for :users, controllers: { sessions: "users/sessions" }

  root :to => "pages#index"

  get 'pages' => 'pages#index'

  get 'hunt' => 'users#hunt'
  get 'sell' => 'users#sell'
  get 'feed' => 'users#feed'

  get 'cart' => 'carts#show'
  get 'wishlist' => 'wishlist#index'
  get 'destroy_wishes' => 'wishes#destroy_wishes'

  resources :orders

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(wish_params.merge({user_id: current_user.id}))

    respond_to do |format|
      if @wish.save
        format.html { redirect_to wishlist_path, notice: 'Product added to wishlist.' }
      else
        format.html { redirect_to products_path, notice: 'Unable to add item to wish list' }
      end
    end
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_wishes
    product_id = params[:product]
    @wishes = Wish.where(product_id: product_id, user_id: current_user.id )
    if @wishes
      @wishes.destroy_all
      notice = "This item has been removed from your wish list";
    else
      notice = "Error deleting item from your wish list";
    end

    respond_to do |format|
      format.html { redirect_to products_path, notice: notice }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_params
      params.permit(:notes, :user_id, :product_id)
    end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_form.html.erb
<%= form_for(@wish, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.form_group :notes do |f| %>
      <%= f.label :notes, class: 'form-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_area :notes, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :user_id do |f| %>
      <%= f.label :user_id, class: 'form-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :user_id, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :product_id do |f| %>
      <%= f.label :product_id, class: 'form-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :product_id, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

  </div>

  <div class="form-actions col-md-offset-3 col-md-9">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", wishes_path, class: 'btn' %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<% @title = "Editing wish" %>

<%= render 'form' %>

app/views/wishes/index.html.erb
<% @title = "My Wish List" %>


<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
        <tr>
          <th>Notes</th>
          <th>User</th>
          <th>Product</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @wishes.each do |wish| %>
        <tr>
          <td><%= wish.notes %></td>
          <td><%= wish.user_id %></td>
          <td><%= wish.product_id %></td>
          <td class="actions">
            <%= link_to icon_tag("eye"), wish, rel: 'tooltip', title: 'Show' %>
            <%= link_to icon_tag("pencil"), edit_wish_path(wish), rel: 'tooltip', title: 'Edit' %>
            <%= link_to icon_tag("trash-o"), wish, rel: 'tooltip', title: 'Delete',
                        data: { confirm: 'Are you sure?' }, method: :delete %>
          </td>
        </tr>
      <% end %>
      <% if @wishes.length == 0 %>
        <tr><td colspan=42 class='text-center'>No wishes.</td></tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/wishes/new.html.erb
<% @title = "New wish" %>

<%= render 'form' %>

app/views/wishes/show.html.erb
<% @title = "Showing wish" %>

<div class="form-horizontal">
  <div class="form-group">
    <label class="col-md-2 form-label">Notes</label>
    <div class="col-md-10 control-label uneditable-input">
      <span>
        <%= @wish.notes %>
      </span>
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-2 form-label">User</label>
    <div class="col-md-10 control-label uneditable-input">
      <span>
        <%= @wish.user_id %>
      </span>
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-2 form-label">Product</label>
    <div class="col-md-10 control-label uneditable-input">
      <span>
        <%= @wish.product_id %>
      </span>
    </div>
  </div>

  <div class="form-actions col-md-offset-2">
    <%= link_to icon_tag("pencil") + ' Edit', edit_wish_path(@wish), class: 'btn btn-primary' %>
    <%= link_to 'Back', wishes_path, class: 'btn' %>
  </div>
</div>