config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :products

  devise_for :users, controllers: { sessions: "users/sessions" }

  root :to => "pages#index"

  get 'pages' => 'pages#index'

  get 'hunt' => 'users#hunt'
  get 'sell' => 'users#sell'
  get 'feed' => 'users#feed'

  get 'cart' => 'carts#show'
  get 'wishlist' => 'wishlist#index'
  get 'destroy_wishes' => 'wishes#destroy_wishes'

  resources :orders

end

app/models/product.rb
class Product < ActiveRecord::Base
  #require 'aws-sdk-v1'
  #require 'aws-sdk'

  belongs_to :order
  belongs_to :user
  has_many :wishes
  has_many :groupies, through: :wishes, source: :user

  before_save :strip_currency_symbol

  validates_presence_of :name, :description, :price
  validates_numericality_of :price




  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  scope :unclaimed, -> { where(order_id: nil, active:true ).order("created_at DESC")}



  def hosted_by?(current_user)
    user_id == current_user.id
  end

  private
    def strip_currency_symbol

    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.unclaimed
  end

  def feed
    @products = Product.unclaimed
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    personal_params = product_params.merge(user_id: current_user.id)
    @product = Product.new(personal_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :active, :order_id, :avatar)
    end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: {multipart: true, class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>





  <div class="form-inputs">

    <%= f.file_field :avatar, class: "no-border" %>



    <%= f.form_group :name do |f| %>
      <%= f.label :name, class: 'form-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :description do |f| %>
        <%= f.label :description, class: 'form-label col-md-2' %>
        <div class='col-md-8'>
          <%= f.text_field :description, class: 'form-control' %>
          <%= f.error_messages %>
        </div>
    <% end %>

    <%= f.form_group :price do |f| %>
      <%= f.label :price, class: 'form-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :price, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :active do |f| %>
      <%= f.label :active, class: 'form-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.check_box :active, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

  </div>

  <div class="form-actions col-md-offset-3 col-md-9">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", products_path, class: 'btn' %>
  </div>



<% end %>

app/views/products/_search_results.html.erb
<% if @products.present? %>
    <% @products.each do |product| %>
        <div class="item">
          <div class="blocked order-title"><%= product.name%></div>
          <div class="blocked order-title"><%= number_to_currency(product.price) %></div>
          <div class="blocked order-image"><%= link_to (image_tag product.avatar.url(:medium)), product_path(product.id) %></div>
        </div>
    <% end %>
<% else %>
  No products match your criteria.
    Please <%= link_to "try again", hunt_path %>
<% end %>

app/views/products/edit.html.erb
<% @title = "Editing product" %>

<%= render 'form' %>

app/views/products/feed.html.erb
<% @title = "Feed" %>

<% content_for :description do %>
    <p></p>
<% end %>

<% content_for :actions do %>
    <%= link_to new_product_path, class: 'btn btn-primary btn-large pull-right' do %>
        <%= icon_tag "plus" %> Add Product
    <% end %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Price</th>
        <th>Active</th>
        <th>Order</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @products.each do |product| %>
          <tr>
            <td><%= image_tag product.avatar.url(:thumb), style:"height:50px" %></td>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= product.active %></td>
            <td><%= product.order_id %></td>
            <td class="actions">
              <%= link_to icon_tag("eye"), product, rel: 'tooltip', title: 'Show' %>
              <% if product.hosted_by?(current_user) %>
                  <%= link_to icon_tag("pencil"), edit_product_path(product), rel: 'tooltip', title: 'Edit' %>
                  <%= link_to icon_tag("trash-o"), product, rel: 'tooltip', title: 'Delete',
                              data: { confirm: 'Are you sure?' }, method: :delete %>
              <% end %>
            </td>
          </tr>
      <% end %>
      <% if @products.length == 0 %>
          <tr><td colspan=42 class='text-center'>No products.</td></tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/products/index.html.erb
<% @title = "Feed" %>

<% content_for :description do %>
  <p></p>
<% end %>

<% content_for :actions do %>
    <%= button_to "Sell a New Item", new_product_path, class: "btn-sq btn-hntrs-red", method: :get %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Price</th>
          <th>Active</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to (image_tag product.avatar.url(:thumb), style:"height:50px"),product %></td>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= product.active %></td>
          <td class="actions">
            <%= link_to icon_tag("eye"), product, rel: 'tooltip', title: 'Show' %>
            <% if product.hosted_by?(current_user) %>
                <%= link_to icon_tag("pencil"), edit_product_path(product), rel: 'tooltip', title: 'Edit' %>
                <%= link_to icon_tag("trash-o"), product, rel: 'tooltip', title: 'Delete',
                            data: { confirm: 'Are you sure?' }, method: :delete %>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% if @products.length == 0 %>
        <tr><td colspan=42 class='text-center'>No products.</td></tr>
      <% end %>
      </tbody>
    </table>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/products/new.html.erb
<% @title = "New product" %>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="product-show">

    <div class="product-column">
      <div id="product-pane" style="background-image: url('<%= @product.avatar %>');"></div>
    </div><!-- end first product column -->

   <div class="product-column">
    <div class="button-container">
      <%# todo: hide below add to cart button also if @product.user == current_user %>
        <% unless @product.order_id.present? %>
          <%= button_to 'Add to Cart', orders_path, class: 'btn-sq btn-buy-now', params: {'product_id' => @product.id}%>
        <% end %>

        <% unless @product.order_id.present? %>
            <%= button_to 'Want', wishes_path, class: 'btn-sq', params: {'product_id' => @product.id}%>
        <% end %>
    </div>

    <div class="show_block">
      <span class="show_title"><%= @product.name %></span>
      <span><%= number_to_currency(@product.price) %></span>
      <span>Seller: <%= @product.user.first_name || @product.user.email %></span>
      <span><%= @product.description %></span>
    </div>
  </div><!-- end second product column -->

</div><!-- end product show -->

</div>