config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :products

  devise_for :users, controllers: { sessions: "users/sessions" }

  root :to => "pages#index"

  get 'pages' => 'pages#index'

  get 'hunt' => 'users#hunt'
  get 'sell' => 'users#sell'
  get 'feed' => 'users#feed'

  get 'cart' => 'carts#show'
  get 'wishlist' => 'wishlist#index'
  get 'destroy_wishes' => 'wishes#destroy_wishes'

  resources :orders

end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>
    
    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>
    
    <%= yield :head %>
  </head>
  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= yield :header %>
      <hr />
    </header>
    
    <%= yield :banner %>

    <div id="main">
      <div class="container">
        <%= render "layouts/flashes" %>

        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->
    
    <%= render "layouts/footer" %>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

  </body>
<% end %>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-danger">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "remove" %> <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "info-sign" %> <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p class="pull-right">
      <%= link_to "Home", root_path %>
      &middot;
      <%= link_to "About", "#" %>
      &middot;
      <%= link_to "Contact Us", "#" %>
      &middot;
      <%= link_to "Terms", "#" %>
      &middot;
      <%= link_to "Privacy", "#" %>
    </p>
    <p>&copy; <%= Date.today.year %> <%= app_name %>. All rights reserved.</p>
    <!--p>Theme by <%#= link_to "MediaBreeze", "http://www.mediabreeze.com" %>.</p-->
  </div> <!-- /.container -->
</footer>

app/views/layouts/_inner_splash.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
    <head>
      <meta charset="utf-8">
      <title><%= [@title, app_name].compact.join(" - ") %></title>
      <%= csrf_meta_tags %>

      <!-- Ensure devices display responsive pages properly -->
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
      <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->

      <!-- Le fonts -->
      <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

      <!-- Le styles -->
      <%= stylesheet_link_tag "application", :media => "all" %>
      <%= yield :styles %>

      <!-- Le fav and touch icons -->
      <%= favicon_link_tag %>
      <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>

      <%= yield :head %>
    </head>
    <body id="splash_body">

        <div id="splash">
          <div class="inner">
            <%= yield %>
          </div>
        </div>


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

    </body>
<% end %>

app/views/layouts/_navbar.html.erb
<%# Top navigation bar containing the main menu of your app. %>
<nav class="navbar navbar-default navbar-inverse">
  <!-- TIP: to unfix the navbar:
    1. remove the 'navbar-fixed-top' class here and
    2. add the 'static-navbar' class to your body tag. -->
  <div class="navbar-inner">
    <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= activatable_li_tag_with_link "Hunt", hunt_path %>
          <%= activatable_li_tag_with_link "Sell", sell_path %>
          <%= activatable_li_tag_with_link "Feed", products_path %>
          <%= activatable_li_tag_with_link "Cart", cart_path %>
          <%= activatable_li_tag_with_link "Profile", profile_path %>
          <% if current_user && current_user.wished_items.present? %>
              <%= activatable_li_tag_with_link "Wishlist", wishlist_path %>
          <% end %>
        </ul>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= yield :navbar %>
        </ul>

    </div> <!-- /.container -->
  </div> <!-- /.navbar-inner -->
</nav> <!-- /.navbar -->

app/views/layouts/_user_nav.html.erb
<%# Links for current user. %>
<div class="navbar-text pull-right">
  <% if user_signed_in? %>
      <%= icon_tag "user" %> Welcome, <strong><%= current_user.first_name || current_user.email %></strong>
      <span class="divider">|</span>
      <li>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      </li>
  <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>
      </li>
  <% end %>

</div>

app/views/layouts/application.html.erb
<% content_for :navbar, render("layouts/user_nav") %>

<%= render :layout => "layouts/base" do %>
  <div class="page-header">
    <div class="row">
      <div class="col-md-7">
        <h2><%= @title %></h2>
        <%= yield :description %>
      </div>
      <div class="col-md-2">
        <%= yield :actions %>
      </div>
    </div>
  </div><!-- /.page-header  -->

  <div class="row">
    <div id="content" class="icol-md-9">
      <%= yield %>
    </div> <!-- /#content -->

    <%# if current_user && current_user.orders.present? %>
        <!--div id="sidebar" class="col-md-3">
          <h6>Cart</h6>
          <p></p>


          <ul class="nav nav-tabs nav-stacked nav-caret-left">
            <%#= activatable_li_tag_with_link "View Cart", cart_path %>
            <%#= activatable_li_tag_with_link "Checkout", "#" %>
            <%#= activatable_li_tag_with_link "A last one", "#" %>
          </ul>
        </div> <!-- /#sidebar -->
    <%# end %>


  </div> <!-- /.row -->
<% end %>

app/views/layouts/home.html.erb
<% content_for :navbar do %>
  <li>
    <%= form_tag "?", :class => "navbar-form hidden-sm navbar-search", role:'search' do %>
      <%= text_field_tag :query, params[:query], :class => "search-query" %>
    <% end %>
  </li>
<% end %>

<%= render :layout => "layouts/base" do %>
  <%= yield %>
<% end %>

app/views/layouts/splash.html.erb
<% content_for :navbar, render("layouts/user_nav") %>

<%= render :layout => "layouts/inner_splash" do %>

        <%= yield %>

<% end %>